In [1]:
import numpy as np
import pandas as pd

## 构造数据

In [2]:
np.random.seed(2019)  # 设置随机因子，让每次随机的结果一样
data = pd.DataFrame(np.random.randint(0, 100, 10), columns=['源数据'])

In [3]:
data

源数据
0   72
1   31
2   37
3   88
4   62
5   24
6   29
7   15
8   12
9   16

## 线性归一化

公式：$X_{n e w}=\frac{X-\min (X)}{\max (X)-\min (X)}$

缩放到[0, 1]之间

In [4]:
from sklearn.preprocessing import MinMaxScaler

In [5]:
mms = MinMaxScaler()
mms.fit(data)  # fit数据结构为DataFrame

MinMaxScaler()

In [6]:
mms.data_max_

array([88.])

In [7]:
mms_data = mms.transform(data)

In [8]:
mms_data

array([[0.78947368],
       [0.25      ],
       [0.32894737],
       [1.        ],
       [0.65789474],
       [0.15789474],
       [0.22368421],
       [0.03947368],
       [0.        ],
       [0.05263158]])

## 标准差标准化

公式：$X_{n e w}=\frac{X-\operatorname{mean}(X)}{\operatorname{std}(X)}$

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
ss = StandardScaler()
ss.fit(data)

StandardScaler()

In [11]:
ss_data = ss.transform(data)

## 绝对值最大标准化

公式：${ X }_{ new }=\frac { X }{ { \vert{ X }\vert}_{ max } }$

缩放到[-1, 1]之间

In [12]:
from sklearn.preprocessing import MaxAbsScaler

In [13]:
mas = MaxAbsScaler()
mas.fit(data)

MaxAbsScaler()

In [18]:
import numpy as np
np.set_printoptions(suppress=True)

mas_data = mas.transform(data)
mas_data

array([[ 0.81818182,  0.00897129,  0.01518862,  0.00929752],
       [ 0.35227273,  0.00284091, -0.00345609,  0.0040031 ],
       [ 0.42045455,  0.00373804, -0.0007276 ,  0.00477789],
       [ 1.        ,  0.01136364,  0.02246461,  0.01136364],
       [ 0.70454545,  0.00747608,  0.01064113,  0.0080062 ],
       [ 0.27272727,  0.00179426, -0.00663934,  0.00309917],
       [ 0.32954545,  0.00254187, -0.00436559,  0.00374483],
       [ 0.17045455,  0.00044856, -0.01073208,  0.00193698],
       [ 0.13636364,  0.        , -0.01209633,  0.00154959],
       [ 0.18181818,  0.00059809, -0.01027733,  0.00206612]])

## 添加数据

In [15]:
data.insert(1, '线性归一化', mms_data)
data.insert(2, '标准差标准化', ss_data)
data.insert(3, '绝对值最大标准化', mas_data)

In [16]:
data

源数据     线性归一化    标准差标准化  绝对值最大标准化
0   72  0.789474  1.336599  0.818182
1   31  0.250000 -0.304136  0.352273
2   37  0.328947 -0.064029  0.420455
3   88  1.000000  1.976886  1.000000
4   62  0.657895  0.936420  0.704545
5   24  0.157895 -0.584262  0.272727
6   29  0.223684 -0.384172  0.329545
7   15  0.039474 -0.944423  0.170455
8   12  0.000000 -1.064477  0.136364
9   16  0.052632 -0.904405  0.181818